defaults: &defaults
 
:development:
  :couchdb:
    :url: http://localhost:5984/slidesink_development
  <<: *defaults
  
:test:
  :couchdb:
    :url: http://localhost:5984/slidesink_test
    <<: *defaults

:production:
  :couchdb:
    :url: http://localhost:5984/slidesink_production
    <<: *defaults